version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    depends_on:
      - postgres
    environment:
      KEY: supersecretkey
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:3000"  # "*" para liberar geral
    volumes:
      - ./uploads:/directus/uploads
    restart: unless-stopped
